require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'cojam_mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )



#  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
#
#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage

#  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

#  pod 'Firebase/Core'
#  pod 'Firebase/Analytics'
#  pod 'Firebase/Messaging'
#
#  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'



  target 'cojam_mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
